routes/web.php
Route::get('/AddWhislist', 'CartController@whislistAdd')->name('whislist.store');

Route::get('/filter_by_price', 'BoutiqueController@filter_by_price')->name('filter_by_price');

Route::get('/sorting', 'ProduitController@sortingBy')->name('sorting');

Route::get('/perpage', 'ProduitController@paginatePage')->name('perpage');

Route::resource('checkout', 'CheckoutController');

Route::get('payement', 'CheckoutController@checkout')->name('payement');

Route::get('/info', 'CheckoutController@dataUser')->name('info');

Route::post('/coupon', 'CouponController@apply')->name('coupon.apply');

//  Route::livewire('/boutique/premiere', Shop::class);
Route::get('/whislist', 'BoutiqueController@whislist')->name('whislist');

//Route::get('/checkout', 'User\AboutController@checkout')->name('checkout');

Route::get('/search', 'ProduitController@search')->name('produit.search');

Route::get('/thank-You', 'CheckoutController@thankyou')->name('thank-You');

Route::resource('boutique', 'BoutiqueController');

Route::post('/payment', 'ShopController@payment')->name('payment');

//Route pour la boutique
Route::get('/accueil-shop', 'ShopController@accueil')->name('accueil-shop');

Route::resource('produit', 'ProduitController');


Route::get('/mail-order', function () {
  $order = App\Models\Commande::find(21);

  return new App\Mail\OrderUser($order);
});

Route::get('/mail-orderadmin', function () {
  $data = App\Models\Adhesion::find(1);

  return new App\Mail\AdhesionMail($data);
});
// Route::get('produi')
/** Fin routes boutique */
Route::resource('carrefour', 'User\CarrefourController')->middleware('auth');
Route::post('/candidature/', 'User\CarrefourController@store')->name('candidat');

Route::get('/profile', 'User\UserController@index')->name('profile')->middleware('auth');
Route::put('/profile/update/{id}', 'User\UserController@update')->name('user.update')->middleware('auth');




/** ============================================ Grouoe routes User ============================*/
Route::group(['prefix' => 'user', 'as' => 'user.', 'middleware' => ['auth', 'user']],function () {

  Route::resource('carrefour', 'CarrefourController');

  //**====================== Route profile =================*/
  Route::get('/profile', 'UserController@profile')->name('profile');
});




/** ============================================ Grouoe routes admin blog ============================*/
Route::group(['prefix' => 'blogger', 'as' => 'blogger.', 'middleware' => ['auth', 'blogger']],function () {
  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::resource('carrefour', 'CarrefourController');

  //**====================== Routes Blog ==================================================*/
  Route::get('/blog.index', 'Admin\BlogController@index')->name('blog.index');

  Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

  Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

  Route::get('/blog/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

  Route::get('/blog/{blog}', 'Admin\BlogController@show')->name('blog.show');

  Route::put('/blog/{blog}', 'Admin\BlogController@update')->name('blog.update');

  Route::put('/blog/{blog}', 'Admin\BlogController@destroy')->name('blog.destroy');

});




/** ============================================ Grouoe routes admin Manager ============================*/
Route::group(['prefix' => 'manage', 'as' => 'manage.', 'middleware' => ['auth', 'manager']],function () {

  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  
  //**============= Routes produits ==========================*/
    
  Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

  Route::post('/store-product', 'ProduitController@store')->name('store-product');

  Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

  Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

  Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

  Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
  
  Route::get('/list-product', 'ProduitController@index')->name('list-product');


    //**======================= Route mesure =========================*/  
  Route::resource('mesure', 'MesureController');
    
    // Ressource de Categorie
  Route::resource('categorie', 'CategorieController');

    //**====================== Routes Offre =========================*/
  Route::get('/list-offre', 'Admin\OffreController@listBlog')->name('list-offre'); 

  Route::post('/insert-offre', 'Admin\OffreController@store')->name('insert-offre');

  Route::get('/edit-offre/{offre}', 'Admin\OffreController@edit')->name('edit-offre');

  Route::get('/show-offre/{offre}', 'Admin\OffreController@show')->name('show-offre');

  Route::put('/update-offre/{offre}', 'Admin\OffreController@update')->name('update-offre');

  Route::put('/destroy-offre/{offre}', 'Admin\OffreController@destroy')->name('destroy-offre');
});





//**================================= Groupe route administration ===================================**// 
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'isadmin']],function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::get('/essai', 'Admin\AdminController@essai')->name('essai');

  //**============================ Routes produits ====================*/
    
    Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

    Route::post('/store-product', 'ProduitController@store')->name('store-product');

    Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

    Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

    Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

    Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
    
    Route::get('/list-product', 'ProduitController@index')->name('list-product');

    //**====================== Routes Blog ===========================*/
    Route::get('/blog/index', 'Admin\BlogController@index')->name('blog.index'); 

    Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

    Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

    Route::get('/blog/edit/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

    Route::get('/blog/show/{blog}', 'Admin\BlogController@show')->name('blog.show');

    Route::put('/blog/update/{blog}', 'Admin\BlogController@update')->name('blog.update');

    Route::put('/blog/delete/{blog}', 'Admin\BlogController@destroy')->name('blog.destroy');

    //**====================== Route Projet ===================== */

    Route::get('/insert-projet', 'Admin\AdminController@insertProjet')->name('insert-projet');

    Route::post('/store-projet', 'ProjetController@store')->name('store-projet');

    Route::get('/edit-projet/{projet}', 'ProjetController@edit')->name('edit-projet'); 

    Route::put('/update-projet/{projet}', 'ProjetController@update')->name('update-projet');

    Route::put('/destroy-projet/{projet}', 'ProjetController@destroy')->name('destroy-projet'); 

    Route::get('/list-projet', 'Admin\AdminController@listProjet')->name('list-projet');


    //**====================== Routes organisme =======================*/

    Route::get('/ajout-organisme', 'Admin\AdminController@createOrganisme')->name('ajout.organisme');

    Route::get('/listOrganisme', 'Admin\AdminController@indexOrganisme')->name('listOrganisme');

    Route::post('/storeOrganisme', 'Admin\AdminController@storeOrganisme')->name('storeOrganisme');

    Route::get('/editOrganisme/{organisme}', 'Admin\AdminController@editOrganisme')->name('editOrganisme');

    Route::put('/updateOrganisme/{organisme}', 'Admin\AdminController@updateOrganisme')->name('updateOrganisme');

    Route::delete('/destroyOrganisme/{organisme}', 'Admin\AdminController@destroyOrganisme')->name('destroyOrganisme');

  //**======================= Route mesures =========================*/  
    Route::resource('mesure', 'MesureController');
    
  // Ressource de Categorie
    Route::resource('categorie', 'CategorieController');

   //**====================== Routes Offres =========================*/
    Route::get('/list-offre', 'Admin\OffreController@listBlog')->name('list-offre');

    Route::get('/offre.index', 'Admin\OffreController@index')->name('offre.index');

  Route::get('/offre.create', 'Admin\OffreController@create')->name('offre.create');

    Route::post('/offre.store', 'Admin\OffreController@store')->name('offre.store');

    Route::get('/offre.edit/{offre}', 'Admin\OffreController@edit')->name('offre.edit');

    Route::get('/offre.show/{offre}', 'Admin\OffreController@show')->name('offre.show');

    Route::put('/offre.update/{offre}', 'Admin\OffreController@update')->name('offre.update');

    Route::put('/offre.destroy/{offre}', 'Admin\OffreController@destroy')->name('offre.destroy');

  //**========================== Routes Services ========================================== */
    Route::get('services', 'Service\ServiceController@index')->name('services.index');

    Route::get('services.create', 'Service\ServiceController@create')->name('services.create');

    Route::post('services.store', 'Service\ServiceController@store')->name('services.store');

    Route::get('services.edit/{Id:id}', 'Service\ServiceController@edit')->name('services.edit');

    Route::patch('services.update', 'Service\ServiceController@upate')->name('services.update');


    Route::delete('services.destroy', 'Service\ServiceController@destroy')->name('services.destroy');

app/Models/Mesure.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Mesure extends Model
{
    protected $fillable = [
        'titre', 'slug'
    ];

    public function produits(){
        return $this->hasMany(Produit::class);
    }
}

app/Http/Controllers/MesureController.php
<?php

namespace App\Http\Controllers;

use App\Models\Mesure;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class MesureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mesures = Mesure::all();

        return view('admin.mesure.liste', compact('mesures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.mesure.mesure');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titre' => 'required',
            'slug' => 'required'
        ]);
        $data = array(
            'titre'=> $request->titre,
        	'slug'=> $request->slug, 
        );
        $cat = Mesure::create($data);
        $cat->save();
        Toastr::success('Sauvegarde reussie.', 'Notification', ["positionClass" => "toast-top-right"]);

       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Mesure $mesure)
    {
        
        return view('admin.mesure.edit', compact('mesure'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Mesure $mes)
    {
       $mesure = Mesure::find($mes);
        
        $mesure->titre = $request->title;
        $mesure->slug = $request->slug;

        $mesure->update();
        Toastr::success('La mesure a ete mise a jour.', 'Notification', ["positionClass" => "toast-top-right"]);

        return redirect('mesure.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/mesure/edit.blade.php
@extends('layouts.navadmin')


@section('content')
        @if(session()->has('message'))
            <div class="alert alert-success center">
                {{ session()->get('message') }}
            </div>
        @endif
        
                <!-- Wizard form -->
                <div class="pd-20 card-box mb-30">
					<div class="clearfix">
						<div class="pull-left">
							<h4 class="text-blue h4">Mesure</h4>
							<p class="mb-30">Enregistrement de mesure</p>
						</div>
						<div class="pull-right">
							<a href="#" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="modal" data-target="#bd-example-modal-lg" type="button" role="button"> Ajouter Categorie</a>
						</div>
					</div>
					
					<div class="wizard-content">
						<form class="tab-wizard wizard-circle wizard" method="post" action="{{route('admin.mesure.update', $mesure)}}" enctype="multipart/form-data">
							@csrf
                            @method('put')
							<h5>Mesure</h5>
							<section>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label >Intiule *</label>
											<input type="text" name="title"  type="text" value="{{ $mesure->titre ? : '' }}" placeholder="Kilogramme" class="form-control" required>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label >Slug *</label>
											<input type="text" class="form-control" name="slug" value="{{ $mesure->slug ? : '' }}"  type="text" placeholder="Kg" required>
										</div>
									</div>
								</div>
							</section>
							<div class="row align-center d-flex">
								<div class="col-sm-6 col-md-4">
									<button type="reset" class="btn btn-danger">Effacer</button>
								</div>
								<div class="col-sm-6 col-md-6">
									<button type="submit" class="btn btn-primary">Enregistrer</button>
								</div>
							</div>
						</form>
					</div>
				</div>

            </div>
        </div>
@endsection

resources/views/admin/mesure/liste.blade.php
@extends('layouts.navadmin')

@section('content')

        <div class="min-height-200px">
            @if(session()->has('message'))
                <div class="alert alert-success center">
                    {{ session()->get('message') }}
                </div>
            @endif
            @if(count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li>
							{{ $error }}
						</li>
					@endforeach
				</ul>
			</div>
		@endif
            <div class="card-box mb-40">
                <div class="clearfix">
                    <div class="pd-20 pull-left">
                        <h4 class="text-blue h4">La liste des mesures</h4>
                    </div>
                    <div class="pull-right">
                        <a href="#" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="modal" data-target="#bd-example-modal-lg" type="button" role="button"> Ajouter Categorie</a>
                    </div>
                </div>
                <div class="pb-20">
                    <table class="data-table table hover multiple-select-row nowrap">
                        <thead>
                            <tr>
                                <th class="table-plus datatable-nosort">Identifiant</th>
                                <th>Nom</th>
                                <th>Slug</th>
                                <th class="datatable-nosort">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach( $mesures as $mesure )
                            <tr>
                                <td>
                                    {{ $mesure->id }}
                                </td>
                                <td>
                                    {{ $mesure->titre }}
                                </td>
                                <td>{{ $mesure->slug }}</td>
                                <td>
                                    <div class="dropdown">
                                        <a class="dropdown-item" href="{{ route('admin.mesure.show', Crypt::encrypt($mesure)) }}"><i class="dw dw-eye"></i> Voir</a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                            <a class="dropdown-item" href="{{route('admin.mesure.edit',  Crypt::encrypt($mesure))}}"><i class="dw dw-edit2"></i> Modifier</a>
                                            <form action="{{ route('admin.mesure.destroy', Crypt::encrypt($mesure)) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="dropdown-item" id="sa-title" type="submit"><i class="dw dw-delete-3"></i> Supprimer</button>

                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                            
                        </tbody>
                        
                    </table>
                
                    {{-- <div class="d-flex justify-content-center">
                        {{ $mesures->links() }}
                    </div> --}}
                </div>

            </div>
            <div class="modal fade bs-example-modal-lg" id="bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myLargeModalLabel">Insertion de mesure</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        </div>
                        <div class="modal-body">
                            <form class="form" method="post" action="{{route('admin.mesure.store')}}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group row">
                                    <label class="col-sm-12 col-md-2 col-form-label">Intitule : </label>
                                    <div class="col-sm-12 col-md-10">
                                        <input class="form-control" name="titre" type="text" placeholder="Agriculture">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-12 col-md-2 col-form-label">Slug</label>
                                    <div class="col-sm-12 col-md-10">
                                        <input class="form-control" name="slug" type="text" placeholder="Le slug">
                                    </div>
                                </div>
                                
                                <div class="row align-center">
                                    <div class="col-sm-6 col-md-4">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                    </div>
                                    <div class="col-sm-6 col-md-6">
                                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        {{-- <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div> --}}
                    </div>
                </div>
            </div>
        </div>
             
@endsection

resources/views/admin/mesure/mesure.blade.php
@extends('layouts.navadmin')


@section('content')
        @if(session()->has('message'))
            <div class="alert alert-success center">
                {{ session()->get('message') }}
            </div>
        @endif
         @if(count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
						<li>
							{{ $error }}
						</li>
					@endforeach
				</ul>
			</div>
		@endif
                <!-- Wizard form -->
                <div class="pd-20 card-box mb-30">
					<div class="clearfix">
						<div class="pull-left">
							<h4 class="text-blue h4">Mesure</h4>
							<p class="mb-30">Enregistrement de mesure</p>
						</div>
						<div class="pull-right">
							<a href="#" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="modal" data-target="#bd-example-modal-lg" type="button" role="button"> Ajouter mesure</a>
						</div>
					</div>
					
					<div class="wizard-content">
						<form class="tab-wizard wizard-circle wizard" method="post" action="{{route('admin.mesure.store')}}" enctype="multipart/form-data">
							@csrf
							<h5>Mesure</h5>
							<section>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label >Intitule *</label>
											<input type="text" name="title"  type="text" placeholder="Kilogramme" class="form-control" required>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label >Symbole de la mesure *</label>
											<input type="text" class="form-control" name="slug"  type="text" placeholder="Kg" required>
										</div>
									</div>
								</div>
							</section>
							<div class="row align-center d-flex">
								<div class="col-sm-6 col-md-4">
									<button type="reset" class="btn btn-danger">Effacer</button>
								</div>
								<div class="col-sm-6 col-md-6">
									<button type="submit" class="btn btn-primary">Enregistrer</button>
								</div>
							</div>
						</form>
					</div>
				</div>

            </div>
        </div>
@endsection