routes/web.php
<?php

use App\Http\Livewire\Shop;
use App\Http\Livewire\ShopComponent;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::get('/code', function(){
  $date = Carbon\Carbon::now()->format('d-m-Y');
  $uniq = mt_rand(1000, 9999);
  $code = 'Sourou_'.$date.'_'.$uniq;
  dd($code);
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');



//Route pour la page de contact
Route::get('/contact', 'ContactController@contact')->name('contact');
Route::post('/send', 'ContactController@store')->name('send.mail');

//Route pour la page a propos
Route::get('/about', 'User\AboutController@about')->name('about');

//Route pour la page adhesion
Route::get('/adhesion', 'User\AboutController@adhesion')->name('adhesion');

Route::get('/conditions-generales-dutilisation', 'ContactController@cgu')->name('cgu');


Route::post('/adhesionsend', 'User\AboutController@preStore')->name('adhesion.store');

Route::post('/adhesion/payment', 'User\AboutController@store')->name('adhesion.payment');




Route::resource('blog/user', 'User\BlogController');



Route::resource('commentaire', 'CommentaireController')->middleware('auth');


/* <-- Routes resources --------------------------------------------------------->*/






//Route pour la page Blog
Route::resource('blog', 'User\BlogController');

Route::resource('projet', 'ProjetController');



//<-- Routes resources fin  --------------------------------------------------------->

Route::get('services', 'Service\ServiceController@services')->name('services');

Route::get('services/single/{id}', 'Service\ServiceController@single')->name('services.single');
Route::post('/subscribe', 'Service\ServiceController@subscribeService')->name('subscribe.service');






Route::post('/newsletter_email','NewsletterController@store')->name('newsletter_email');



Route::get('/projet-vue', 'ProjetController@index')->name('projet-vue');
Route::get('/projet-search', 'ProjetController@search')->name('projet-search');
Route::resource('/projet', 'ProjetController');
Route::get('/partenaire', 'ShopController@partenaire')->name('partenaire');
Route::get('/ong', 'ShopController@ong')->name('ong');
Route::get('/organisme', 'ShopController@organisme')->name('organisme');
//Route::get('/accueil', 'ShopController@accueil')->name('accueil-shop');

Route::get('/details', 'User\AboutController@details')->name('details');


//**====================================== Boutique routes =================================**/

// Cart routes
Route::resource('cart', 'CartController');
Route::get('/cart.store', 'CartController@store')->name('store.cart');
Route::patch('/panier/{rowId}', 'CartController@update')->name('cart.update');

Route::get('/AddWhislist', 'CartController@whislistAdd')->name('whislist.store');

Route::get('/filter_by_price', 'BoutiqueController@filter_by_price')->name('filter_by_price');

Route::get('/sorting', 'ProduitController@sortingBy')->name('sorting');

Route::get('/perpage', 'ProduitController@paginatePage')->name('perpage');

Route::resource('checkout', 'CheckoutController');

Route::get('payement', 'CheckoutController@checkout')->name('payement');

Route::get('/info', 'CheckoutController@dataUser')->name('info');

Route::post('/coupon', 'CouponController@apply')->name('coupon.apply');

//  Route::livewire('/boutique/premiere', Shop::class);
Route::get('/whislist', 'BoutiqueController@whislist')->name('whislist');

//Route::get('/checkout', 'User\AboutController@checkout')->name('checkout');

Route::get('/search', 'ProduitController@search')->name('produit.search');

Route::get('/thank-You', 'CheckoutController@thankyou')->name('thank-You');

Route::resource('boutique', 'BoutiqueController');

Route::post('/payment', 'ShopController@payment')->name('payment');

//Route pour la boutique
Route::get('/accueil-shop', 'ShopController@accueil')->name('accueil-shop');

Route::resource('produit', 'ProduitController');


Route::get('/mail-order', function () {
  $order = App\Models\Commande::find(21);

  return new App\Mail\OrderUser($order);
});

Route::get('/mail-orderadmin', function () {
  $data = App\Models\Adhesion::find(1);

  return new App\Mail\AdhesionMail($data);
});
// Route::get('produi')
/** Fin routes boutique */
Route::resource('carrefour', 'User\CarrefourController')->middleware('auth');
Route::post('/candidature/', 'User\CarrefourController@store')->name('candidat');

Route::get('/profile', 'User\UserController@index')->name('profile')->middleware('auth');
Route::put('/profile/update/{id}', 'User\UserController@update')->name('user.update')->middleware('auth');




/** ============================================ Grouoe routes User ============================*/
Route::group(['prefix' => 'user', 'as' => 'user.', 'middleware' => ['auth', 'user']],function () {

  Route::resource('carrefour', 'CarrefourController');

  //**====================== Route profile =================*/
  Route::get('/profile', 'UserController@profile')->name('profile');
});




/** ============================================ Grouoe routes admin blog ============================*/
Route::group(['prefix' => 'blogger', 'as' => 'blogger.', 'middleware' => ['auth', 'blogger']],function () {
  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::resource('carrefour', 'CarrefourController');

  //**====================== Routes Blog ==================================================*/
  Route::get('/blog.index', 'Admin\BlogController@index')->name('blog.index');

  Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

  Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

  Route::get('/blog/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

  Route::get('/blog/{blog}', 'Admin\BlogController@show')->name('blog.show');

  Route::put('/blog/{blog}', 'Admin\BlogController@update')->name('blog.update');

  Route::put('/blog/{blog}', 'Admin\BlogController@destroy')->name('blog.destroy');

});




/** ============================================ Grouoe routes admin Manager ============================*/
Route::group(['prefix' => 'manage', 'as' => 'manage.', 'middleware' => ['auth', 'manager']],function () {

  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  
  //**============= Routes produits ==========================*/
    
  Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

  Route::post('/store-product', 'ProduitController@store')->name('store-product');

  Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

  Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

  Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

  Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
  
  Route::get('/list-product', 'ProduitController@index')->name('list-product');


    //**======================= Route mesure =========================*/  
  Route::resource('mesure', 'MesureController');
    
    // Ressource de Categorie
  Route::resource('categorie', 'CategorieController');

    //**====================== Routes Offre =========================*/
  Route::get('/list-offre', 'Admin\OffreController@listBlog')->name('list-offre'); 

  Route::post('/insert-offre', 'Admin\OffreController@store')->name('insert-offre');

  Route::get('/edit-offre/{offre}', 'Admin\OffreController@edit')->name('edit-offre');

  Route::get('/show-offre/{offre}', 'Admin\OffreController@show')->name('show-offre');

  Route::put('/update-offre/{offre}', 'Admin\OffreController@update')->name('update-offre');

  Route::put('/destroy-offre/{offre}', 'Admin\OffreController@destroy')->name('destroy-offre');
});





//**================================= Groupe route administration ===================================**// 
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'isadmin']],function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::get('/essai', 'Admin\AdminController@essai')->name('essai');

  //**============================ Routes produits ====================*/
    
    Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

    Route::post('/store-product', 'ProduitController@store')->name('store-product');

    Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

    Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

    Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

    Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
    
    Route::get('/list-product', 'ProduitController@index')->name('list-product');

    //**====================== Routes Blog ===========================*/
    Route::get('/blog/index', 'Admin\BlogController@index')->name('blog.index'); 

    Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

    Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

    Route::get('/blog/edit/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

    Route::get('/blog/show/{blog}', 'Admin\BlogController@show')->name('blog.show');

    Route::put('/blog/update/{blog}', 'Admin\BlogController@update')->name('blog.update');

app/Models/Projet.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Projet extends Model
{
    protected $fillable = [
        'title', 'image', 'description', 'auteur',
    ];

    protected $table = 'projets';

     public function categories(){
        return  $this->belongsToMany('App\Models\Categorie',  'categorie_projet');
    }
}

app/Http/Controllers/ProjetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\models\Groupe;
use App\Models\Projet;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Crypt;

class ProjetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs_recent = Blog::all()->take(3)->sortBy('created_at');
        $projets = Projet::paginate('6');
        return view('pages.projet.projet', compact('blogs_recent', 'projets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groupes = Categorie::all();
        return view('admin.projet.insert-projet', compact('groupes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'image' => 'required|mimes:png,jpg,jpeg',
            'auteur' => 'required',
            'description' => 'required',
        ]);

        $data = array(
        	'title'=> $request->title,
            'image'=> $request->file('image')->store('projets', 'public'),
        	'auteur'=> $request->auteur,
            'description'=> $request->description,
        );
        $offre = Projet::create($data);
        $offre->categories()->attach($request->categorie);
            Toastr::success('L\'enregistrement a reussi.!!!', 'Notification', ["positionClass" => "toast-top-right"]);
       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($projet)
    {      
        $projet = Crypt::decrypt($projet);
        $blogs = Blog::all()->take(3)->sortBy('created_at');
        return view('pages.projet.detail', compact('projet', 'blogs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $projet= Crypt::decrypt($id);

        return view('admin.projet.edit', compact('projet'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $projet = Crypt::decrypt($id);
        
            $projet->title = $request->title;
            $projet->image = $request->file('image')->store('projets', 'public');
            $projet->auteur = $request->auteur;
            $projet->description = $request->description;
            $projet->status = $request->status;
            $projet->update();
           Toastr::success('Le projet a ete mise a jour.!!!', 'Notification', ["positionClass" => "toast-top-right"]);

        return redirect('admin.list-projet');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $projet = Crypt::decrypt($id);
       $projet->delete();
       Toastr::success('Le projet a été bien supprimée.!!!', 'Notification', ["positionClass" => "toast-top-right"]);
       return redirect('admin.list-projet');

    }

    public function search(){
        request()->validate([
            'search' => 'required|min:3'
        ]);
        $q = request()->input('search');
        $blogs = Blog::all()->take(3)->sortBy('created_at');

        //dd($q);
       $projets = Projet::where('title', 'like', "%$q%")->orWhere('description', 'like', "%$q%")->paginate(4);
        return view('pages.projet.projet', compact('blogs'))->with('projets', $projets);
    }
}

resources/views/pages/projet/detail.blade.php
@extends('layouts.nav')

@push('css')
    <style>
      .cus {
        background-color: #fffff;
        border-color: #ffffff;
      }
    </style>
@endpush

@section('content')

<section class="hero-wrap hero-wrap-2" style="background-image: url('account/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
            <p class="breadcrumbs mb-2"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Detail Projet <i class="ion-ios-arrow-forward"></i></span></p>
          <h1 class="mb-0 bread">Detail Projet</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section ftco-degree-bg">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 ftco-animate">
            <p>
            <img src="{{ asset('storage/' . $projet->image) }}" alt="" class="img-fluid">
          </p>
          <h1 class="mb-3">{{$projet->title}}</h1>
          
          <p>{!! $projet->description !!}</p>
          
        </div> <!-- .col-md-8 -->
        <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
          <div class="sidebar-box">
            <form action="{{ route('projet-search') }}" class="search-form">
              <div class="form-group">
                <button class="fa fa-search cus" type="submit"></button>
                <input type="text" name="search" class="form-control" placeholder="Entrez un mot" type="search" value="{{ request()->search ?? ''}}">
              </div>
            </form>
          </div>
          <div class="sidebar-box ftco-animate">
            <div class="categories">
              <h3>Categories</h3>
              @foreach($categ as $categorie)
              <li><a href="#">{{$categorie->nom}} <span class="ion-ios-arrow-forward"></span></a></li>
              @endforeach
            </div>
          </div>

          <div class="sidebar-box ftco-animate">
            <h3>Recent Blog</h3>
            @foreach($blogs as $blog)
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({{ asset('storage/' . $blog->image) }});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">{!! substr(strip_tags($blog->description, '(...)'), 0, 80) !!}</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span>{{ Carbon\Carbon::parse($blog->created_at)->locale('fr_FR')->isoFormat('Do MMMM YYYY') }}</a></div>
                    <div><a href="#"><span class="icon-person"></span> {{ $blog->auteur }}</a></div>
                    {{-- <div><a href="#"><span class="icon-chat"></span> 19</a></div> --}}
                  </div>
                </div>
              </div>
            @endforeach
          <div class="sidebar-box ftco-animate">
            <h3>Tag Cloud</h3>
            <div class="tagcloud">
              <a href="#" class="tag-cloud-link">home</a>
              <a href="#" class="tag-cloud-link">builder</a>
              <a href="#" class="tag-cloud-link">build</a>
              <a href="#" class="tag-cloud-link">create</a>
              <a href="#" class="tag-cloud-link">make</a>
              <a href="#" class="tag-cloud-link">construction</a>
              <a href="#" class="tag-cloud-link">house</a>
              <a href="#" class="tag-cloud-link">architect</a>
            </div>
          </div>

          {{-- <div class="sidebar-box ftco-animate">
            <h3>Paragraph</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
          </div>
        </div> --}}

      </div>
    </div>
  </section> <!-- .section -->

  @include('layouts.newsletter')

@endsection

resources/views/pages/projet/projet.blade.php
@extends('layouts.nav')

@section('content')

<section class="hero-wrap hero-wrap-2" style="background-image: url('account/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
            <p class="breadcrumbs mb-2"><span class="mr-2"><a href="index.html">Accueil <i class="ion-ios-arrow-forward"></i></a></span> <span>Projets <i class="ion-ios-arrow-forward"></i></span></p>
          <h1 class="mb-0 bread">Nos Projets</h1>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 ftco-animate">
          @foreach($projets as $projet)
              <div class="cases-wrap d-md-flex align-items-center">
                <div class="img" style="background-image: url({{ asset('storage/' . $projet->image) }});"></div>
                <div class="text pl-md-5">
                    <span class="cat">Projet </span>
                    <h2>{{ $projet->title }}</h2>
                    <p>{!! substr(strip_tags($projet->description, '(...)'), 0, 180) !!}</p>
                    <p><a href="{{ route('projet.show', Crypt::encrypt($projet)) }}" class="btn btn-primary">En savoir +</a></p>
                </div>
              </div>
          @endforeach
          

          {{-- {{$projets->links('pagination::blog-paginate')}} --}}

        </div> <!-- .col-md-8 -->
        <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
          <div class="sidebar-box">
            <form action="{{ route('projet-search') }}" class="search-form">
              <div class="form-group d-flex">
                <input name="search" class="form-control" placeholder="Entrez un mot" type="search" value="{{ request()->search ?? ''}}">
                <button class="btn btn-primary p-4" style="margin-left: 0.5rem; height: 3.5rem;"><i class="ti-search"></i></button>
              </div>
            </form>
          </div>
          <div class="sidebar-box ftco-animate">
            <div class="categories">
              <h3>Categories</h3>
              @foreach($categ as $categorie)
                <li><a href="#">{{$categorie->nom}} <span class="ion-ios-arrow-forward"></span></a></li>
              @endforeach
              
              {{-- <li><a href="#">Mental &amp; Physical Care <span class="ion-ios-arrow-forward"></span></a></li>
              <li><a href="#">People &amp; Relationships <span class="ion-ios-arrow-forward"></span></a></li>
              <li><a href="#">Life Coaching <span class="ion-ios-arrow-forward"></span></a></li> --}}
            </div>
          </div>

          <div class="sidebar-box ftco-animate">
            <h3>Blog récent</h3>
            @foreach($blogs_recent as $blog)
            <div class="block-21 mb-4 d-flex">
              <a class="blog-img mr-4" style="background-image: url({{ asset('storage/' . $blog->image) }});"></a>
              <div class="text">
                <h3 class="heading"><a href="#">{!! substr(strip_tags($blog->description, '(...)'), 0, 80) !!}</a></h3>
                <div class="meta">
                  <div><a href="#"><span class="icon-calendar"></span>{{ Carbon\Carbon::parse($blog->created_at)->locale('fr_FR')->isoFormat('Do MMMM YYYY') }}</a></div>
                  <div><a href="#"><span class="icon-person"></span> {{ $blog->auteur }}</a></div>
                  <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                </div>
              </div>
            </div>
            @endforeach
            {{-- <div class="block-21 mb-4 d-flex">
              <a class="blog-img mr-4" style="background-image: url(account/images/image_2.jpg);"></a>
              <div class="text">
                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                <div class="meta">
                  <div><a href="#"><span class="icon-calendar"></span> Jan. 30, 2020</a></div>
                  <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                  <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                </div>
              </div>
            </div>
            <div class="block-21 mb-4 d-flex">
              <a class="blog-img mr-4" style="background-image: url(account/images/image_3.jpg);"></a>
              <div class="text">
                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                <div class="meta">
                  <div><a href="#"><span class="icon-calendar"></span> Jan. 30, 2020</a></div>
                  <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                  <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                </div>
              </div>
            </div>
          </div> --}}

          <div class="sidebar-box ftco-animate">
            <h3>Nuage de tags</h3>
            <div class="tagcloud">
              <a href="#" class="tag-cloud-link">agriculture</a>
              <a href="#" class="tag-cloud-link">pisciculture</a>
              <a href="#" class="tag-cloud-link">elevage</a>
              <a href="#" class="tag-cloud-link">aquaculture</a>
              <a href="#" class="tag-cloud-link">horticulture</a>
              <a href="#" class="tag-cloud-link">jardinage</a>
              <a href="#" class="tag-cloud-link">formation</a>
              <a href="#" class="tag-cloud-link">viticulture</a>
            </div>
          </div>

          <div class="sidebar-box ftco-animate">
            <h3>Informations</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
          </div>
        </div>

      </div>
    </div>
  </section> <!-- .section -->

  @include('layouts.newsletter')


@endsection