routes/web.php
Route::get('/AddWhislist', 'CartController@whislistAdd')->name('whislist.store');

Route::get('/filter_by_price', 'BoutiqueController@filter_by_price')->name('filter_by_price');

Route::get('/sorting', 'ProduitController@sortingBy')->name('sorting');

Route::get('/perpage', 'ProduitController@paginatePage')->name('perpage');

Route::resource('checkout', 'CheckoutController');

Route::get('payement', 'CheckoutController@checkout')->name('payement');

Route::get('/info', 'CheckoutController@dataUser')->name('info');

Route::post('/coupon', 'CouponController@apply')->name('coupon.apply');

//  Route::livewire('/boutique/premiere', Shop::class);
Route::get('/whislist', 'BoutiqueController@whislist')->name('whislist');

//Route::get('/checkout', 'User\AboutController@checkout')->name('checkout');

Route::get('/search', 'ProduitController@search')->name('produit.search');

Route::get('/thank-You', 'CheckoutController@thankyou')->name('thank-You');

Route::resource('boutique', 'BoutiqueController');

Route::post('/payment', 'ShopController@payment')->name('payment');

//Route pour la boutique
Route::get('/accueil-shop', 'ShopController@accueil')->name('accueil-shop');

Route::resource('produit', 'ProduitController');


Route::get('/mail-order', function () {
  $order = App\Models\Commande::find(21);

  return new App\Mail\OrderUser($order);
});

Route::get('/mail-orderadmin', function () {
  $data = App\Models\Adhesion::find(1);

  return new App\Mail\AdhesionMail($data);
});
// Route::get('produi')
/** Fin routes boutique */
Route::resource('carrefour', 'User\CarrefourController')->middleware('auth');
Route::post('/candidature/', 'User\CarrefourController@store')->name('candidat');

Route::get('/profile', 'User\UserController@index')->name('profile')->middleware('auth');
Route::put('/profile/update/{id}', 'User\UserController@update')->name('user.update')->middleware('auth');




/** ============================================ Grouoe routes User ============================*/
Route::group(['prefix' => 'user', 'as' => 'user.', 'middleware' => ['auth', 'user']],function () {

  Route::resource('carrefour', 'CarrefourController');

  //**====================== Route profile =================*/
  Route::get('/profile', 'UserController@profile')->name('profile');
});




/** ============================================ Grouoe routes admin blog ============================*/
Route::group(['prefix' => 'blogger', 'as' => 'blogger.', 'middleware' => ['auth', 'blogger']],function () {
  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::resource('carrefour', 'CarrefourController');

  //**====================== Routes Blog ==================================================*/
  Route::get('/blog.index', 'Admin\BlogController@index')->name('blog.index');

  Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

  Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

  Route::get('/blog/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

  Route::get('/blog/{blog}', 'Admin\BlogController@show')->name('blog.show');

  Route::put('/blog/{blog}', 'Admin\BlogController@update')->name('blog.update');

  Route::put('/blog/{blog}', 'Admin\BlogController@destroy')->name('blog.destroy');

});




/** ============================================ Grouoe routes admin Manager ============================*/
Route::group(['prefix' => 'manage', 'as' => 'manage.', 'middleware' => ['auth', 'manager']],function () {

  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  
  //**============= Routes produits ==========================*/
    
  Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

  Route::post('/store-product', 'ProduitController@store')->name('store-product');

  Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

  Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

  Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

  Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
  
  Route::get('/list-product', 'ProduitController@index')->name('list-product');


    //**======================= Route mesure =========================*/  
  Route::resource('mesure', 'MesureController');
    
    // Ressource de Categorie
  Route::resource('categorie', 'CategorieController');

    //**====================== Routes Offre =========================*/
  Route::get('/list-offre', 'Admin\OffreController@listBlog')->name('list-offre'); 

  Route::post('/insert-offre', 'Admin\OffreController@store')->name('insert-offre');

  Route::get('/edit-offre/{offre}', 'Admin\OffreController@edit')->name('edit-offre');

  Route::get('/show-offre/{offre}', 'Admin\OffreController@show')->name('show-offre');

  Route::put('/update-offre/{offre}', 'Admin\OffreController@update')->name('update-offre');

  Route::put('/destroy-offre/{offre}', 'Admin\OffreController@destroy')->name('destroy-offre');
});





//**================================= Groupe route administration ===================================**// 
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'isadmin']],function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::get('/essai', 'Admin\AdminController@essai')->name('essai');

  //**============================ Routes produits ====================*/
    
    Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

    Route::post('/store-product', 'ProduitController@store')->name('store-product');

    Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

    Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

    Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

    Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
    
    Route::get('/list-product', 'ProduitController@index')->name('list-product');

    //**====================== Routes Blog ===========================*/
    Route::get('/blog/index', 'Admin\BlogController@index')->name('blog.index'); 

    Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

    Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

    Route::get('/blog/edit/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

    Route::get('/blog/show/{blog}', 'Admin\BlogController@show')->name('blog.show');

    Route::put('/blog/update/{blog}', 'Admin\BlogController@update')->name('blog.update');

    Route::put('/blog/delete/{blog}', 'Admin\BlogController@destroy')->name('blog.destroy');

    //**====================== Route Projet ===================== */

    Route::get('/insert-projet', 'Admin\AdminController@insertProjet')->name('insert-projet');

    Route::post('/store-projet', 'ProjetController@store')->name('store-projet');

    Route::get('/edit-projet/{projet}', 'ProjetController@edit')->name('edit-projet'); 

    Route::put('/update-projet/{projet}', 'ProjetController@update')->name('update-projet');

    Route::put('/destroy-projet/{projet}', 'ProjetController@destroy')->name('destroy-projet'); 

    Route::get('/list-projet', 'Admin\AdminController@listProjet')->name('list-projet');


    //**====================== Routes organisme =======================*/

    Route::get('/ajout-organisme', 'Admin\AdminController@createOrganisme')->name('ajout.organisme');

    Route::get('/listOrganisme', 'Admin\AdminController@indexOrganisme')->name('listOrganisme');

    Route::post('/storeOrganisme', 'Admin\AdminController@storeOrganisme')->name('storeOrganisme');

    Route::get('/editOrganisme/{organisme}', 'Admin\AdminController@editOrganisme')->name('editOrganisme');

    Route::put('/updateOrganisme/{organisme}', 'Admin\AdminController@updateOrganisme')->name('updateOrganisme');

    Route::delete('/destroyOrganisme/{organisme}', 'Admin\AdminController@destroyOrganisme')->name('destroyOrganisme');

  //**======================= Route mesures =========================*/  
    Route::resource('mesure', 'MesureController');
    
  // Ressource de Categorie
    Route::resource('categorie', 'CategorieController');

   //**====================== Routes Offres =========================*/
    Route::get('/list-offre', 'Admin\OffreController@listBlog')->name('list-offre');

    Route::get('/offre.index', 'Admin\OffreController@index')->name('offre.index');

  Route::get('/offre.create', 'Admin\OffreController@create')->name('offre.create');

    Route::post('/offre.store', 'Admin\OffreController@store')->name('offre.store');

    Route::get('/offre.edit/{offre}', 'Admin\OffreController@edit')->name('offre.edit');

    Route::get('/offre.show/{offre}', 'Admin\OffreController@show')->name('offre.show');

    Route::put('/offre.update/{offre}', 'Admin\OffreController@update')->name('offre.update');

    Route::put('/offre.destroy/{offre}', 'Admin\OffreController@destroy')->name('offre.destroy');

  //**========================== Routes Services ========================================== */
    Route::get('services', 'Service\ServiceController@index')->name('services.index');

    Route::get('services.create', 'Service\ServiceController@create')->name('services.create');

    Route::post('services.store', 'Service\ServiceController@store')->name('services.store');

    Route::get('services.edit/{Id:id}', 'Service\ServiceController@edit')->name('services.edit');

    Route::patch('services.update', 'Service\ServiceController@upate')->name('services.update');


    Route::delete('services.destroy', 'Service\ServiceController@destroy')->name('services.destroy');

app/Models/Offre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Offre extends Model
{
    protected $guarded = [];
    
    protected $casts = [
        'expiration' => 'datetime',
        'publie' => 'datetime',
    ];

     public function users(){
        return  $this->belongsToMany('App\Models\User', 'offre_user');
    }

    public function categories(){
        return  $this->belongsToMany('App\Models\Categorie',  'categorie_offre');
    }
}

app/Http/Controllers/Admin/OffreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Offre;
use App\Models\Candidature;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;

class OffreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $offres = Offre::paginate(10);
       return view('admin.offre.offre', compact('offres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categorie::all();
        return view('admin.offre.ajout', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'image' => 'required|mimes:png,jpg,jpeg',
            'entreprise' => 'required',
            'poste' => 'required',
            'expiration' => 'required',
            'description' => 'required',
            'status' => 'required',
        ]);
        $date = Carbon::now()->format('d-m-Y');
        $uniq = mt_rand(1000, 9999);
        $code = 'OFR_' . $date . '_' . $uniq;
        $data = array(
            'reference'=> $code,
        	'title'=> $request->title,
        	'entreprise'=> $request->entreprise,
            'image'=> $request->file('image')->store('offres', 'public'),
            'status' => $request->status,
        	'poste'=> $request->poste,
        	'expiration'=> $request->expiration,
            'description'=> $request->description,
        );
        $offre = Offre::create($data);
        $offre->categories()->attach($request->categorie);
        Toastr::success('L\'enregistrement a reussi.!!!', 'Notification', ["positionClass" => "toast-top-right"]);

       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $offre = Offre::find($id);
        //dd($produit);

        return view('admin.offre.show', compact('offre'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $offre = Offre::find($id);
        return view('admin.offre.edit', compact('offre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $offre)
    {
        $off = Offre::find($offre);
        $off->title = $request->title;
        $off->entreprise = $request->entreprise;
        $off->image =  $request->file('image')->store('offres', 'public');
        $off->expiration =  $request->expiration;
        $off->description =  $request->description;
        $off->update();
        $off->categories()->sync($request->categorie);
        Toastr::success('L\'enregistrement a reussi.!!!', 'Notification', ["positionClass" => "toast-top-right"]);

       return redirect('admin.offre.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Crypt::decrypt($id);
        //dd($produit);

        return redirect('admin.list-offre')->with('success', );
    }

    public function candidature(Request $request){

        $data  = array(
            'nom_user' => Auth::user()->nom,
            'id_offre' => $request->id_offre,
        );

        Candidature::create($data);
        User::attach($request->offre);

    }
}

resources/views/admin/offre/ajout.blade.php
@extends('layouts.navadmin')


@section('content')
@if(session()->has('message'))
<div class="row pull-right">
    <div class="alert alert-success alert-dismissible fade show col-md-4" role="alert">
        <strong>Holy guacamole!</strong> {{ session()->get('message') }}.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
    </div>
</div>
@endif
@if(count($errors) > 0)
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>
            {{ $error }}
        </li>
        @endforeach
    </ul>
</div>
@endif
{!! Toastr::message() !!}
<!-- Wizard form -->
<div class="pd-20 card-box mb-30">
    <div class="clearfix">
        <div class="pull-left">
            <h4 class="text-blue h4">Offre</h4>
            <p class="mb-30">Enregistrement de Offre</p>
        </div>
    </div>

    <div class="wizard-content">
        <form class="form" method="post" action="{{route('admin.offre.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ __('Titre') }}</label>
                        <input class="form-control" name="title" type="text" placeholder="APAID">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{ __('Nom de l\'entreprise') }}</label>
                        <input class="form-control" name="entreprise" type="text" placeholder="APAID">
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>{{__('Date d\'expiration')}}</label>
                        <input class="form-control" name="expiration" placeholder="Date d'expiration" type="date">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Categorie offre* :</label>
                        <select class="custom-select2 form-control" multiple="multiple" style="width: 100%;" name="categorie[]"
                            required>
                            <option value="{{ '' }}">Choisir...</option>
                            @foreach($categories as $categorie)
                            <option value="{{ $categorie->id  }}">{{ $categorie->nom }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Choisir une image</label>
                        <div class="custom-file">
                            <input type="file" name="image" class="col-12 custom-file-input">
                            <label class="custom-file-label">Choisir une image</label>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>{{__("Poste")}}</label>
                            <input class="form-control" name="poste" placeholder="Charge en communication" type="text">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="weight-600">Status</label>
                        <div class="custom-control custom-radio mb-5">
                            <input type="radio" id="customRadio1" name="status" value="1" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio1">Actif</label>
                        </div>
                        <div class="custom-control custom-radio mb-5">
                            <input type="radio" id="customRadio2" name="status" value="0" class="custom-control-input">
                            <label class="custom-control-label" for="customRadio2">Non actif</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="summernote form-control border-radius-0" name="description"
                            placeholder="Entrez la description"></textarea>
                    </div>
                </div>
            </div>
        
            <div class="row align-center">
                <div class="col-sm-6 col-md-4">
                    <button type="reset" class="btn btn-danger">Effacer</button>
                </div>
                <div class="col-sm-6 col-md-6">
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                </div>
            </div>
        </form>
    </div>
</div>

</div>
</div>
@endsection

resources/views/admin/offre/edit.blade.php
@extends('layouts.navadmin')


@section('content')
    <div class="pd-ltr-20 xs-pd-20-10">
        @if(session()->has('message'))
            <div class="alert alert-success center">
                {{ session()->get('message') }}
            </div>
        @endif
        <div class="min-height-300px">
            <div class="pd-20 card-box p-10 mb-30">
                <div class="clearfix">
                    <div class="pull-left">
                        <h4 class="text-blue h4">Offres</h4>
                        <p class="mb-30">Insertion des offres</p>
                    </div>
                    <div class="pull-right">
                        {{-- <a href="#" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="modal" data-target="#bd-example-modal-lg" type="button" role="button"> Aouter Categorie</a> --}}
                    </div>
                </div>
                    <form class="form" method="post" action="{{route('admin.offre.update', $offre)}}" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="row">
						    <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Titre de l\'offre') }}</label>
                                    <input class="form-control" name="title" value="{{$offre->title ? : ''}}" type="text" placeholder="APAID">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Nom de l\'entreprise') }}</label>
                                    <input class="form-control" name="entreprise" value="{{$offre->entreprise ? : ''}}" type="text"
                                            placeholder="APAID">
                                </div>
                            </div>
                        </div>
                        <div class="row">
						    <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Date d\'expiration') }}</label>
                                    <input class="form-control" name="expiration" value="{{$offre->expiration ? : ''}}" placeholder="Nom de l'auteur" type="date">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label> Choisir une image</label>
                                    <input type="file" name="image" class="col-12 custom-file-input"
                                            value="{{ asset('storage/'. $offre->image) }}">
                                    <label class="custom-file-label">Choisir une image</label>
                                    <img class="col-sm-4" src="{{ asset('storage/' . $offre->image) ? : '' }}" alt="Image produit"
                                        style="width:120px; height:100px;">
                                </div>
                            </div>
                        </div>
                        {{-- <div class="row"> --}}
						    
						    {{-- <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-sm-12 col-md-2 col-form-label">{{ ('Date de publication') }}</label>
                                    <div class="col-sm-12 col-md-10">
                                        <input class="form-control" name="domaine" value="{{$offre->publie ? : ''}}"  type="date">
                                    </div>
                                </div>
                            </div> --}}
                        {{-- </div> --}}
                        {{-- <div class="row"> --}}
						    {{-- <div class="col-md-6">
                               <div class="form-group">
                                    <label class="col-sm-12 col-md-2 col-form-label">{{ ('Experiences') }}</label>
                                    <div class="col-sm-12 col-md-10">
                                        <input class="form-control" name="domaine" value="{{$offre->experience ? : ''}}"  type="text">
                                    </div>
                                </div>
                            </div> --}}
						    {{-- <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-sm-12 col-md-2 col-form-label">{{ ('Niveau') }}</label>
                                    <div class="col-sm-12 col-md-10">
                                        <input class="form-control" name="domaine" value="{{$offre->publie ? : ''}}"  type="text">
                                    </div>
                                </div>
                            </div> --}}
                        {{-- </div> --}}
                        <div class="form-group row">
                            <label>Description</label>
                                <textarea class="summernote form-control border-radius-2" name="description" placeholder="Entrez la description">{{$offre->description ? : ''}}</textarea>
                        </div>
                        
                        <div class="row align-center">
                            <div class="col-sm-6 col-md-4">
                                <button type="reset" class="btn btn-danger">Effacer</button>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <button type="submit" class="btn btn-primary">Enregistrer</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/offre/offre.blade.php
@extends('layouts.navadmin')

@section('content')
    <div class="card-box mb-30">
        <div class="pd-20">
            <h4 class="text-blue h4">Liste des offres</h4>
        </div>
        <div class="pb-20">
            <table class="table  data-table-export nowrap">
                <thead>
                    <tr>
                        <th class="table-plus datatable-nosort">Reference</th>
                        <th>Entreprise</th>
                        <th>Domaine</th>
                        <th>Date limite</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($offres as $offre)
                        <tr>
                            <td class="table-plus">{{$offre->reference}}</td>
                            <td>{{$offre->entreprise}}</td>
                            <td>{{$offre->poste}}</td>
                            <td>{{$offre->expiration}}</td>
                            <td>
                            <div class="row">
                                <a class="btn btn-secondary" role="button" href="{{ route('admin.offre.show', $offre) }}"><i class="dw dw-eye"></i></a>
                                <a class="btn btn-warning" role="button" href="{{ route('admin.offre.edit', $offre) }}"><i class="icon-copy dw dw-edit-1"></i></a>
                                <form action="{{ route('admin.offre.destroy', $offre) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" id="sa-title" type="submit"><i class="dw dw-delete-3"></i></button>

                                </form>
                            </div>
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/offre/show.blade.php
@extends('layouts.navadmin')


@section('content')
        <div class="min-height-200px">
				<div class="page-header">
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<div class="title">
								<h4>Detail offre</h4>
							</div>
							<nav aria-label="breadcrumb" role="navigation">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="index.html">Accueil</a></li>
									<li class="breadcrumb-item active" aria-current="page">Detail offre</li>
								</ol>
							</nav>
						</div>
					</div>
				</div>
				<div class="blog-wrap">
					<div class="container pd-0">
						<div class="row">
							<div class="col-md-8 col-sm-12">
								<div class="blog-detail card-box overflow-hidden mb-30">
									<div class="blog-img">
										<img src="{{asset('storage/'. $offe->image)}}" alt="">
									</div>
									<div class="blog-caption">
                                        <h4 class="mb-10">{{$offre->title}}</h4>
										<p>{{$offre->description}}</p>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-sm-12">
								<div class="card-box mb-30">
									<h5 class="pd-20 h5 mb-0">Categories</h5>
									<div class="list-group">
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">HTML <span class="badge badge-primary badge-pill">7</span></a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">Css <span class="badge badge-primary badge-pill">10</span></a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between active">Bootstrap <span class="badge badge-primary badge-pill">8</span></a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">jQuery <span class="badge badge-primary badge-pill">15</span></a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">Design <span class="badge badge-primary badge-pill">5</span></a>
									</div>
								</div>
								<div class="card-box mb-30">
									<h5 class="pd-20 h5 mb-0">Latest Post</h5>
									<div class="latest-post">
										<ul>
											<li>
												<h4><a href="#">Ut enim ad minim veniam, quis nostrud exercitation ullamco</a></h4>
												<span>HTML</span>
											</li>
											<li>
												<h4><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit</a></h4>
												<span>Css</span>
											</li>
											<li>
												<h4><a href="#">Ut enim ad minim veniam, quis nostrud exercitation ullamco</a></h4>
												<span>jQuery</span>
											</li>
											<li>
												<h4><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit</a></h4>
												<span>Bootstrap</span>
											</li>
											<li>
												<h4><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit</a></h4>
												<span>Design</span>
											</li>
										</ul>
									</div>
								</div>
								<div class="card-box overflow-hidden">
									<h5 class="pd-20 h5 mb-0">Archives</h5>
									<div class="list-group">
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">January 2020</a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">February 2020</a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">March 2020</a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">April 2020</a>
										<a href="#" class="list-group-item d-flex align-items-center justify-content-between">May 2020</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

@endsection