routes/web.php
<?php

use App\Http\Livewire\Shop;
use App\Http\Livewire\ShopComponent;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::get('/code', function(){
  $date = Carbon\Carbon::now()->format('d-m-Y');
  $uniq = mt_rand(1000, 9999);
  $code = 'Sourou_'.$date.'_'.$uniq;
  dd($code);
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');



//Route pour la page de contact
Route::get('/contact', 'ContactController@contact')->name('contact');
Route::post('/send', 'ContactController@store')->name('send.mail');

//Route pour la page a propos
Route::get('/about', 'User\AboutController@about')->name('about');

//Route pour la page adhesion
Route::get('/adhesion', 'User\AboutController@adhesion')->name('adhesion');

Route::get('/conditions-generales-dutilisation', 'ContactController@cgu')->name('cgu');


Route::post('/adhesionsend', 'User\AboutController@preStore')->name('adhesion.store');

Route::post('/adhesion/payment', 'User\AboutController@store')->name('adhesion.payment');




Route::resource('blog/user', 'User\BlogController');



Route::resource('commentaire', 'CommentaireController')->middleware('auth');


/* <-- Routes resources --------------------------------------------------------->*/






//Route pour la page Blog
Route::resource('blog', 'User\BlogController');

Route::resource('projet', 'ProjetController');



//<-- Routes resources fin  --------------------------------------------------------->

Route::get('services', 'Service\ServiceController@services')->name('services');

Route::get('services/single/{id}', 'Service\ServiceController@single')->name('services.single');
Route::post('/subscribe', 'Service\ServiceController@subscribeService')->name('subscribe.service');






Route::post('/newsletter_email','NewsletterController@store')->name('newsletter_email');



Route::get('/projet-vue', 'ProjetController@index')->name('projet-vue');
Route::get('/projet-search', 'ProjetController@search')->name('projet-search');
Route::resource('/projet', 'ProjetController');
Route::get('/partenaire', 'ShopController@partenaire')->name('partenaire');
Route::get('/ong', 'ShopController@ong')->name('ong');
Route::get('/organisme', 'ShopController@organisme')->name('organisme');
//Route::get('/accueil', 'ShopController@accueil')->name('accueil-shop');

Route::get('/details', 'User\AboutController@details')->name('details');


//**====================================== Boutique routes =================================**/

// Cart routes
Route::resource('cart', 'CartController');
Route::get('/cart.store', 'CartController@store')->name('store.cart');
Route::patch('/panier/{rowId}', 'CartController@update')->name('cart.update');

Route::get('/AddWhislist', 'CartController@whislistAdd')->name('whislist.store');

Route::get('/filter_by_price', 'BoutiqueController@filter_by_price')->name('filter_by_price');

Route::get('/sorting', 'ProduitController@sortingBy')->name('sorting');

Route::get('/perpage', 'ProduitController@paginatePage')->name('perpage');

Route::resource('checkout', 'CheckoutController');

Route::get('payement', 'CheckoutController@checkout')->name('payement');

Route::get('/info', 'CheckoutController@dataUser')->name('info');

Route::post('/coupon', 'CouponController@apply')->name('coupon.apply');

//  Route::livewire('/boutique/premiere', Shop::class);
Route::get('/whislist', 'BoutiqueController@whislist')->name('whislist');

//Route::get('/checkout', 'User\AboutController@checkout')->name('checkout');

Route::get('/search', 'ProduitController@search')->name('produit.search');

Route::get('/thank-You', 'CheckoutController@thankyou')->name('thank-You');

Route::resource('boutique', 'BoutiqueController');

Route::post('/payment', 'ShopController@payment')->name('payment');

//Route pour la boutique
Route::get('/accueil-shop', 'ShopController@accueil')->name('accueil-shop');

Route::resource('produit', 'ProduitController');


Route::get('/mail-order', function () {
  $order = App\Models\Commande::find(21);

  return new App\Mail\OrderUser($order);
});

Route::get('/mail-orderadmin', function () {
  $data = App\Models\Adhesion::find(1);

  return new App\Mail\AdhesionMail($data);
});
// Route::get('produi')
/** Fin routes boutique */
Route::resource('carrefour', 'User\CarrefourController')->middleware('auth');
Route::post('/candidature/', 'User\CarrefourController@store')->name('candidat');

Route::get('/profile', 'User\UserController@index')->name('profile')->middleware('auth');
Route::put('/profile/update/{id}', 'User\UserController@update')->name('user.update')->middleware('auth');




/** ============================================ Grouoe routes User ============================*/
Route::group(['prefix' => 'user', 'as' => 'user.', 'middleware' => ['auth', 'user']],function () {

  Route::resource('carrefour', 'CarrefourController');

  //**====================== Route profile =================*/
  Route::get('/profile', 'UserController@profile')->name('profile');
});




/** ============================================ Grouoe routes admin blog ============================*/
Route::group(['prefix' => 'blogger', 'as' => 'blogger.', 'middleware' => ['auth', 'blogger']],function () {
  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::resource('carrefour', 'CarrefourController');

  //**====================== Routes Blog ==================================================*/
  Route::get('/blog.index', 'Admin\BlogController@index')->name('blog.index');

  Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

  Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

  Route::get('/blog/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

  Route::get('/blog/{blog}', 'Admin\BlogController@show')->name('blog.show');

  Route::put('/blog/{blog}', 'Admin\BlogController@update')->name('blog.update');

  Route::put('/blog/{blog}', 'Admin\BlogController@destroy')->name('blog.destroy');

});




/** ============================================ Grouoe routes admin Manager ============================*/
Route::group(['prefix' => 'manage', 'as' => 'manage.', 'middleware' => ['auth', 'manager']],function () {

  Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  
  //**============= Routes produits ==========================*/
    
  Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

  Route::post('/store-product', 'ProduitController@store')->name('store-product');

  Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

  Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

  Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

  Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
  
  Route::get('/list-product', 'ProduitController@index')->name('list-product');


    //**======================= Route mesure =========================*/  
  Route::resource('mesure', 'MesureController');
    
    // Ressource de Categorie
  Route::resource('categorie', 'CategorieController');

    //**====================== Routes Offre =========================*/
  Route::get('/list-offre', 'Admin\OffreController@listBlog')->name('list-offre'); 

  Route::post('/insert-offre', 'Admin\OffreController@store')->name('insert-offre');

  Route::get('/edit-offre/{offre}', 'Admin\OffreController@edit')->name('edit-offre');

  Route::get('/show-offre/{offre}', 'Admin\OffreController@show')->name('show-offre');

  Route::put('/update-offre/{offre}', 'Admin\OffreController@update')->name('update-offre');

  Route::put('/destroy-offre/{offre}', 'Admin\OffreController@destroy')->name('destroy-offre');
});





//**================================= Groupe route administration ===================================**// 
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'isadmin']],function () {
    Route::get('/dashboard', 'Admin\AdminController@index')->name('dashboard');
  Route::get('/essai', 'Admin\AdminController@essai')->name('essai');

  //**============================ Routes produits ====================*/
    
    Route::get('/insert-product', 'Admin\AdminController@insertProduct')->name('insert-product');

    Route::post('/store-product', 'ProduitController@store')->name('store-product');

    Route::get('/edit-product/{produit}', 'ProduitController@edit')->name('edit-product');

    Route::get('/show-product/{produit}', 'ProduitController@show')->name('show-product');

    Route::put('/update-product/{produit}', 'ProduitController@update')->name('update-product');

    Route::delete('/destroy-product/{produit}', 'ProduitController@destroy')->name('destroy-product');
    
    Route::get('/list-product', 'ProduitController@index')->name('list-product');

    //**====================== Routes Blog ===========================*/
    Route::get('/blog/index', 'Admin\BlogController@index')->name('blog.index'); 

    Route::get('/blog', 'Admin\BlogController@create')->name('blog.create');

    Route::post('/blog', 'Admin\BlogController@store')->name('blog.store');

    Route::get('/blog/edit/{blog}', 'Admin\BlogController@edit')->name('blog.edit');

    Route::get('/blog/show/{blog}', 'Admin\BlogController@show')->name('blog.show');

    Route::put('/blog/update/{blog}', 'Admin\BlogController@update')->name('blog.update');

app/Http/Controllers/User/AboutController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Mail\AdhesionMail;
use App\Models\Adhesion;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class AboutController extends Controller
{
    public function about(){
        return view('pages.about');
    }

    public function adhesion(){
        return view('pages.adhesion');
    }

    public function preStore(Request $request) {

        $data = [
            'nom' => $request->nom,
            'responsable' => $request->responsable,
            'domaine' => $request->domaine,
            'pays' => $request->pays,
            'ville' => $request->ville,
            'demande' => $request->file('demande')->store('demande', 'public'),
            'objectifs' => $request->objectif,
            'realisation' => $request->realisation,
            'email' => $request->email,
            'phone' => $request->phone,
       ];
        Validator::make($data, [
            'nom' => ['required', 'string', 'max:255'],
            'responsable' => ['required', 'string', 'max:255'],
            'pays' => ['required', 'string', 'max:255'],
            'ville' => ['required', 'string', 'max:100'],
            'domaine' => ['required', 'string', 'max:255'],
            'pays' => ['required', 'string', 'max:255'],
            'realisation' => ['required',],
            'demande' => ['required', 'mimes:doc,pdf,docx', 'max:10000'],
            'objectifs' => ['required', 'string'],
        ]);

        $res = Adhesion::create($data);
        $res->save();

        Mail::to('zoschrispuce@gmail.com')->send(new AdhesionMail($data));

        Toastr::success('Votre demande à été envoyé', 'Notification', ["positionClass" => "toast-top-right"]);

        return \redirect()->back();
    }

    public function store(Request $request){

       $adhesion = new Adhesion();
       $adhesion->nom = $request->session()->get('nom');
       $adhesion->responsable = $request->session()->get('responsable');
       $adhesion->domaine = $request->session()->get('domaine');
       $adhesion->pays = $request->session()->get('pays');
       $adhesion->ville = $request->session()->get('ville');
       $adhesion->demande = $request->session()->get('demande')->file('demande')->store('demande', 'public');
       $adhesion->objectif = $request->session()->get('objectif')->file('objectif')->store('objectif', 'public');
       $adhesion->realisation = $request->session()->get('realisation');
       Toastr::success('L\'enregistrement a reussi.!!!', 'Notification', ["positionClass" => "toast-top-right"]);

       return redirect('/adhesion');
    }

    public function details(){
        return view('boutique.details');
    }

    public function checkout(){
        return view('boutique.checkout');
    }

    public function cart(){
        return view('boutique.cart');
    }
}

app/Http/Controllers/User/BlogController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Blog;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::paginate(6);
        //  $date = Carbon::parse('22-11-2021')->locale('fr_FR')->isoFormat('LLLL');
        //  dd($date);
        return view('pages.blog.blog', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::find($id);
        return view('pages.blog.blog-single', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/CarrefourController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Candidature;
use Illuminate\Http\Request;
use App\Models\Offre;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;

class CarrefourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $offres = Offre::paginate(6);
        return view('pages.offre.carrefour', compact('offres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       if (Auth::user()->cv) {
            $candidat =  Candidature::create([
                'nom_candidat' => Auth::user()->name,
                'reference_offre' => $request->ref,
                'cv_candidat' => Auth::user()->cv,
                'sexe' => Auth::user()->sexe,
            ]);
            $candidat->save();
       } else {
            Toastr::success('Veuillez telecharger votre Cv.', 'Notification', ["positionClass" => "toast-top-right"]);
            return redirect('profile');
       }
       

        Toastr::success('Votre candidature a ete bien envoyee.', 'Notification', ["positionClass" => "toast-top-right"]);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $offre = Offre::findOrFail($id);
        return view('pages.offre.detail', compact('offre'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/edit.blade.php
@extends('layouts.navadmin')


@section('content')
        @if(session()->has('message'))
            <div class="alert alert-success center">
                {{ session()->get('message') }}
            </div>
        @endif

        <div class="min-height-300px">
			 <!-- Wizard form -->
                <div class="pd-20 card-box mb-30">
					<div class="clearfix">
						<div class="pull-left">
							<h4 class="text-blue h4">Modifier Utilisteur</h4>
							<p class="mb-30">Modification</p>
						</div>
					</div>
					
					<div class="wizard-content">
						<form class="tab-wizard wizard-circle wizard" method="post" action="{{route('user.edit', Crypt::encrypt($user))}}" enctype="multipart/form-data">
							@method('put')
							@csrf
							<h5>Utilisateur {{ $user->name }}</h5>
							<section>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label >Nom utilisateur *</label>
											<input type="text" name="nom" placeholder="Nom du organisme" value="{{ $user->name ? : '' }}" class="form-control" required>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label >Email *</label>
											<input type="text" class="form-control" name="responsable" value="{{ $user->email ? : '' }}" placeholder="Le nom du responsable" required>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label>{{__('Domaine d\'intervention* :')}}</label>
											<input type="text" class="form-control" name="phone" value="{{ $user->phone ? : '' }}"  type="text" required>
										</div>
									</div>
                                    <div class="col-md-6">
										<div class="form-group">
											<label>{{__('Domaine d\'intervention* :')}}</label>
											<input type="text" class="form-control" name="pays" value="{{ $user->pays ? : '' }}"  type="text" required>
										</div>
									</div>
									
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label>Sexe :</label>
											<select class="custom-select2 form-control" style="width: 100%;" name="sexe" required>
                                                <option>Selectionnez le sexe</option>
												<option value="masculin" {{ old('sexe', isset($user->sexe) == "masculin" ? 'selected' : '') ? 'selected' : '' }}>Masculin</option>
												<option value="feminin" {{ old('sexe', isset($user->sexe) == "feminin" ? 'selected' : '') ? 'selected' : ''  }}>Feminin</option>
											</select>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label>Role :</label>
											<select class="custom-select2 form-control" style="width: 100%;" name="role" required>
                                                <option>Selectionnez le role</option>
												<option value="admin" {{ old('role', isset($user->role) == "admin" ? 'selected' : '') ? 'selected' : '' }}>Admin</option>
												<option value="blogger" {{ old('role', isset($user->role) == "blogger" ? 'selected' : '') ? 'selected' : ''  }}>Blogger</option>
                                                <option value="manage" {{ old('role', isset($user->role) == "manage" ? 'selected' : '') ? 'selected' : ''  }}>Manager</option>
                                                <option value="user" {{ old('role', isset($user->role) == "user" ? 'selected' : '') ? 'selected' : ''  }}>User</option>
											</select>
										</div>
									</div>
								</div>
								
							</section>
							
							
							<div class="row align-center d-flex">
								<div class="col-sm-6 col-md-4">
									<button type="reset" class="btn btn-danger">Effacer</button>
								</div>
								<div class="col-sm-6 col-md-6">
									<button type="submit" class="btn btn-primary">Enregistrer</button>
								</div>
							</div>
						</form>
					</div>
				</div>
            </div>
        </div>
@endsection

resources/views/admin/user/user.blade.php
@extends('layouts.navadmin')

@section('content')

        @if(session()->has('message'))
            <div class="alert alert-success center">
                {{ session()->get('message') }}
            </div>
        @endif
        <div class="card-box mb-40">
            <h2 class="h4 pd-20">Gestion Utilisateur</h2>
        
            <table class="data-table table nowrap">
                <thead>
                    <tr>
                        <th class="table-plus datatable-nosort">Users</th>
                        <th>Nom</th>
                        <th>E-mail</th>
                        <th>Sexe</th>
                        <th>Phone</th>
                        <th>Pays</th>
                        <th>Role</th>
                        <th class="datatable-nosort">Action</th>
                    </tr>
                </thead>
                
                <tbody>
                @foreach( $users as $user )
                    <tr>
                        <td class="table-plus">
                            <img src="deskapp/vendors/images/product-1.jpg" width="70" height="70" alt="">
                        </td>
                        <td>
                           {{ $user->name }}
                        </td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->sexe }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>{{ $user->pays }}</td>
                        <td>@if($user->role == 'admin') <span  class="badge badge-success">{{ __('Admin') }} </span>
                            @elseif ($user->role == 'user')
                            <span  class="badge badge-warning">{{ __("User") }}</span>
                            @elseif ($user->role == 'manage')
                            <span  class="badge badge-primary">{{ __("Manager") }}</span>
                            @elseif ($user->role == 'blogger')
                            <span  class="badge badge-info">{{ __("Blogger") }}</span>
                            @endif </td>
                        <td>
                            
                            <div class="dropdown">
                                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                    <i class="dw dw-more"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                    <a class="dropdown-item" href="{{route('user.edit', Crypt::encrypt($user))}}"><i class="dw dw-edit2"></i> Modifier</a>
                                    <a class="dropdown-item" href="{{ route('user.destroy', $user) }}"><i class="dw dw-delete-3"></i> Supprimer</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            
            </table>
        </div>
    </div>
</div>
              
@endsection